#!/bin/bash

unset -v xml
unset -v actionGraph
unset -v dflow
unset -v arr

function iterate_over_cl()
{
   unset -v arr	
   arr=("$OPTARG")	
   until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z $(eval "echo \${$OPTIND}") ]; do
        arr+=($(eval "echo \${$OPTIND}"))
        OPTIND=$((OPTIND + 1))
   done
   echo ${arr}
}


while getopts ":p:D:g:djem" opt
   do
     case $opt in
        d ) dflow=1;;
        p ) xml="$(iterate_over_cl)"
	     for i in "${xml[@]}"
	     do
		 echo "Parsing $i"
		 STARTTIME=`date +%s.%N`
		 swipl --quiet -s 'src/xml2tree.pl' -t "parse_activity_graph('${i}')"
		 if [[ ${dflow} -eq 1 ]]; then
		     graph="src/autogen/graph_"$(echo ${i} | sed 's/.*\///' | sed 's/\.dive/\.pl/')
		     echo "Dataflow analysis of ${graph}"
		     swipl --quiet -s 'src/dataflowAnalysis.pl' -t "main('${graph}')" --
		 fi
		  ENDTIME=`date +%s.%N`
		  TIMEDIFF=`echo "$ENDTIME-$STARTTIME" | bc | awk -F"." '{print $1"."substr($2,1,3)}'`
		  time
		  echo "Analysis time is: $TIMEDIFF"
		 swipl --quiet -s 'src/tools.pl' -t "draw_action_graph('${i}')"
	     done
	     swipl --quiet -s 'src/buildRacerScript.pl' -t "build_all_task_spec" --   
             ;;
	D ) actionGraph="$(iterate_over_cl)"
            ;;    
	j)  swipl --quiet -s 'src/buildRacerScript.pl' -t "build_compile_commands" --   
             ;;
	     
        e)  STARTTIME=`date +%s.%N`
	    swipl --quiet -s 'src/buildRacerScript.pl' -t "build_all_events" --   
	    ENDTIME=`date +%s.%N`
	    TIMEDIFF=`echo "$ENDTIME-$STARTTIME" | bc | awk -F"." '{print $1"."substr($2,1,3)}'`
	    echo "Analysis time is: $TIMEDIFF"
             ;;
  	m)  swipl --quiet -s 'src/buildRacerScript.pl' -t "getEventMap" --   
             ;;
     esac
done

for i in "${actionGraph[@]}"
do
	echo "Dataflow analysis of ${i}"
	swipl --quiet -s 'src/dataflowAnalysis.pl' -t "main('${i}')" --
done

#grep -E '\breal\b' errorlog
# time